# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trackBall.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftrackBall.proto\x12\x05\x63\x61\x63he\"0\n\x10trackBallRequest\x12\x0e\n\x06tensor\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\"%\n\x15\x64\x65leteDetectorRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\"\n\x11trackBallResponse\x12\r\n\x05point\x18\x01 \x01(\x0c\"&\n\x16\x64\x65leteDetectorResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\xab\x01\n\ttrackBall\x12M\n\x16\x66indTennisBallPosition\x12\x17.cache.trackBallRequest\x1a\x18.cache.trackBallResponse\"\x00\x12O\n\x0e\x64\x65leteDetector\x12\x1c.cache.deleteDetectorRequest\x1a\x1d.cache.deleteDetectorResponse\"\x00\x62\x06proto3')



_TRACKBALLREQUEST = DESCRIPTOR.message_types_by_name['trackBallRequest']
_DELETEDETECTORREQUEST = DESCRIPTOR.message_types_by_name['deleteDetectorRequest']
_TRACKBALLRESPONSE = DESCRIPTOR.message_types_by_name['trackBallResponse']
_DELETEDETECTORRESPONSE = DESCRIPTOR.message_types_by_name['deleteDetectorResponse']
trackBallRequest = _reflection.GeneratedProtocolMessageType('trackBallRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRACKBALLREQUEST,
  '__module__' : 'trackBall_pb2'
  # @@protoc_insertion_point(class_scope:cache.trackBallRequest)
  })
_sym_db.RegisterMessage(trackBallRequest)

deleteDetectorRequest = _reflection.GeneratedProtocolMessageType('deleteDetectorRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDETECTORREQUEST,
  '__module__' : 'trackBall_pb2'
  # @@protoc_insertion_point(class_scope:cache.deleteDetectorRequest)
  })
_sym_db.RegisterMessage(deleteDetectorRequest)

trackBallResponse = _reflection.GeneratedProtocolMessageType('trackBallResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRACKBALLRESPONSE,
  '__module__' : 'trackBall_pb2'
  # @@protoc_insertion_point(class_scope:cache.trackBallResponse)
  })
_sym_db.RegisterMessage(trackBallResponse)

deleteDetectorResponse = _reflection.GeneratedProtocolMessageType('deleteDetectorResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEDETECTORRESPONSE,
  '__module__' : 'trackBall_pb2'
  # @@protoc_insertion_point(class_scope:cache.deleteDetectorResponse)
  })
_sym_db.RegisterMessage(deleteDetectorResponse)

_TRACKBALL = DESCRIPTOR.services_by_name['trackBall']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACKBALLREQUEST._serialized_start=26
  _TRACKBALLREQUEST._serialized_end=74
  _DELETEDETECTORREQUEST._serialized_start=76
  _DELETEDETECTORREQUEST._serialized_end=113
  _TRACKBALLRESPONSE._serialized_start=115
  _TRACKBALLRESPONSE._serialized_end=149
  _DELETEDETECTORRESPONSE._serialized_start=151
  _DELETEDETECTORRESPONSE._serialized_end=189
  _TRACKBALL._serialized_start=192
  _TRACKBALL._serialized_end=363
# @@protoc_insertion_point(module_scope)
