# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MainServer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10MainServer.proto\x12\x04main\",\n\x17StartProcessRequestData\x12\x11\n\tProcessId\x18\x01 \x01(\x01\"+\n\x16StopProcessRequestData\x12\x11\n\tProcessId\x18\x01 \x01(\x01\")\n\x14MergeDataRequestData\x12\x11\n\tProcessId\x18\x01 \x01(\x01\"H\n\x18StartProcessResponseData\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\t\x12\r\n\x05\x46rame\x18\x03 \x01(\t\"8\n\x17StopProcessResponseData\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x08\"(\n\x15MergeDataResponseData\x12\x0f\n\x07Message\x18\x01 \x01(\t2\xf5\x01\n\nMainServer\x12Q\n\x0cStartProcess\x12\x1d.main.StartProcessRequestData\x1a\x1e.main.StartProcessResponseData\"\x00\x30\x01\x12L\n\x0bStopProcess\x12\x1c.main.StopProcessRequestData\x1a\x1d.main.StopProcessResponseData\"\x00\x12\x46\n\tMergeData\x12\x1a.main.MergeDataRequestData\x1a\x1b.main.MergeDataResponseData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MainServer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTPROCESSREQUESTDATA._serialized_start=26
  _STARTPROCESSREQUESTDATA._serialized_end=70
  _STOPPROCESSREQUESTDATA._serialized_start=72
  _STOPPROCESSREQUESTDATA._serialized_end=115
  _MERGEDATAREQUESTDATA._serialized_start=117
  _MERGEDATAREQUESTDATA._serialized_end=158
  _STARTPROCESSRESPONSEDATA._serialized_start=160
  _STARTPROCESSRESPONSEDATA._serialized_end=232
  _STOPPROCESSRESPONSEDATA._serialized_start=234
  _STOPPROCESSRESPONSEDATA._serialized_end=290
  _MERGEDATARESPONSEDATA._serialized_start=292
  _MERGEDATARESPONSEDATA._serialized_end=332
  _MAINSERVER._serialized_start=335
  _MAINSERVER._serialized_end=580
# @@protoc_insertion_point(module_scope)
