# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predictFallPosition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19predictFallPosition.proto\x12\x05\x63\x61\x63he\"6\n$predictFallPositionControllerRequest\x12\x0e\n\x06points\x18\x01 \x01(\x0c\"7\n%predictFallPositionControllerResponse\x12\x0e\n\x06points\x18\x01 \x01(\x0c\x32\x93\x01\n\x13predictFallPosition\x12|\n\x1dpredictFallPositionController\x12+.cache.predictFallPositionControllerRequest\x1a,.cache.predictFallPositionControllerResponse\"\x00\x62\x06proto3')



_PREDICTFALLPOSITIONCONTROLLERREQUEST = DESCRIPTOR.message_types_by_name['predictFallPositionControllerRequest']
_PREDICTFALLPOSITIONCONTROLLERRESPONSE = DESCRIPTOR.message_types_by_name['predictFallPositionControllerResponse']
predictFallPositionControllerRequest = _reflection.GeneratedProtocolMessageType('predictFallPositionControllerRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTFALLPOSITIONCONTROLLERREQUEST,
  '__module__' : 'predictFallPosition_pb2'
  # @@protoc_insertion_point(class_scope:cache.predictFallPositionControllerRequest)
  })
_sym_db.RegisterMessage(predictFallPositionControllerRequest)

predictFallPositionControllerResponse = _reflection.GeneratedProtocolMessageType('predictFallPositionControllerResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTFALLPOSITIONCONTROLLERRESPONSE,
  '__module__' : 'predictFallPosition_pb2'
  # @@protoc_insertion_point(class_scope:cache.predictFallPositionControllerResponse)
  })
_sym_db.RegisterMessage(predictFallPositionControllerResponse)

_PREDICTFALLPOSITION = DESCRIPTOR.services_by_name['predictFallPosition']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTFALLPOSITIONCONTROLLERREQUEST._serialized_start=36
  _PREDICTFALLPOSITIONCONTROLLERREQUEST._serialized_end=90
  _PREDICTFALLPOSITIONCONTROLLERRESPONSE._serialized_start=92
  _PREDICTFALLPOSITIONCONTROLLERRESPONSE._serialized_end=147
  _PREDICTFALLPOSITION._serialized_start=150
  _PREDICTFALLPOSITION._serialized_end=297
# @@protoc_insertion_point(module_scope)
