apiVersion: v1
kind: Service
metadata:
  name: mainservicepool
spec:
  clusterIP: None
  selector:
    app: mainservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 50011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainservicedeployment
  labels:
    team: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainservice
  template:
    metadata:
      labels:
        app: mainservice
    spec:
      containers:
      - name: mainservice
        image: 127.0.0.1:10000/main-service
        ports:
          - containerPort: 50011
        resources:
          requests:
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "1Gi"