# Generated by the Services Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clients.PredictFallPosition.predictFallPosition_pb2 as predictFallPosition__pb2


class predictFallPositionStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predictFallPositionController = channel.unary_unary(
                '/cache.predictFallPosition/predictFallPositionController',
                request_serializer=predictFallPosition__pb2.predictFallPositionControllerRequest.SerializeToString,
                response_deserializer=predictFallPosition__pb2.predictFallPositionControllerResponse.FromString,
                )


class predictFallPositionServicer(object):
    """Service
    """

    def predictFallPositionController(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_predictFallPositionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predictFallPositionController': grpc.unary_unary_rpc_method_handler(
                    servicer.predictFallPositionController,
                    request_deserializer=predictFallPosition__pb2.predictFallPositionControllerRequest.FromString,
                    response_serializer=predictFallPosition__pb2.predictFallPositionControllerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.predictFallPosition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class predictFallPosition(object):
    """Service
    """

    @staticmethod
    def predictFallPositionController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.predictFallPosition/predictFallPositionController',
            predictFallPosition__pb2.predictFallPositionControllerRequest.SerializeToString,
            predictFallPosition__pb2.predictFallPositionControllerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
