FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
 
WORKDIR /src
COPY ./TennisWeb6/UI/*.csproj ./
RUN dotnet restore
 
COPY ./TennisWeb6/ ./
RUN dotnet build UI/UI.csproj -o /app -r linux-x64 /p:PublishReadyToRun=true
RUN dotnet publish UI/UI.csproj -o /publish -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true


FROM mcr.microsoft.com/dotnet/aspnet:6.0 as base
COPY --from=build /publish /app
WORKDIR /app
EXPOSE 80
HEALTHCHECK CMD curl --fail http://localhost || exit 1  
 
CMD ["./UI/UI.csproj"]


