apiVersion: v1
kind: Service
metadata:
  name: postgresservicepool
spec:
  clusterIP: None
  selector:
    app: postgresservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 50041
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresservicedeployment
  labels:
    team: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresservice
  template:
    metadata:
      labels:
        app: postgresservice
    spec:
      containers:
      - name: postgresservice
        image: 127.0.0.1:10000/postgres-service
        ports:
          - containerPort: 50041
