# Generated by the Services Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clients.ProcessData.processData_pb2 as processData__pb2


class ProcessDataStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.processAOS = channel.unary_unary(
                '/cache.ProcessData/processAOS',
                request_serializer=processData__pb2.processAOSRequest.SerializeToString,
                response_deserializer=processData__pb2.processAOSResponse.FromString,
                )


class ProcessDataServicer(object):
    """Service
    """

    def processAOS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'processAOS': grpc.unary_unary_rpc_method_handler(
                    servicer.processAOS,
                    request_deserializer=processData__pb2.processAOSRequest.FromString,
                    response_serializer=processData__pb2.processAOSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.ProcessData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessData(object):
    """Service
    """

    @staticmethod
    def processAOS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.ProcessData/processAOS',
            processData__pb2.processAOSRequest.SerializeToString,
            processData__pb2.processAOSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
