# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafkaConsumer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13kafkaConsumer.proto\x12\x08\x63onsumer\"B\n\x0f\x43onsumerRequest\x12\x11\n\ttopicName\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x03\" \n\x10\x43onsumerResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32V\n\rkafkaConsumer\x12\x45\n\x08\x63onsumer\x12\x19.consumer.ConsumerRequest\x1a\x1a.consumer.ConsumerResponse\"\x00\x30\x01\x62\x06proto3')



_CONSUMERREQUEST = DESCRIPTOR.message_types_by_name['ConsumerRequest']
_CONSUMERRESPONSE = DESCRIPTOR.message_types_by_name['ConsumerResponse']
ConsumerRequest = _reflection.GeneratedProtocolMessageType('ConsumerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERREQUEST,
  '__module__' : 'kafkaConsumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.ConsumerRequest)
  })
_sym_db.RegisterMessage(ConsumerRequest)

ConsumerResponse = _reflection.GeneratedProtocolMessageType('ConsumerResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERRESPONSE,
  '__module__' : 'kafkaConsumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.ConsumerResponse)
  })
_sym_db.RegisterMessage(ConsumerResponse)

_KAFKACONSUMER = DESCRIPTOR.services_by_name['kafkaConsumer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSUMERREQUEST._serialized_start=33
  _CONSUMERREQUEST._serialized_end=99
  _CONSUMERRESPONSE._serialized_start=101
  _CONSUMERRESPONSE._serialized_end=133
  _KAFKACONSUMER._serialized_start=135
  _KAFKACONSUMER._serialized_end=221
# @@protoc_insertion_point(module_scope)
