version: '3.7'
services:
  # SERVERS
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    networks:
      - tennisnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tenis
      POSTGRES_PASSWORD: 2sfcNavA89A294V4
      POSTGRES_DB: tenis
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  broker0:
  postgresql:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/postgresql"
      
networks:
  tennisnet:
    driver: bridge