version: '3.7'
services:
  #! TOOLS
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - tennisnet
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
  broker:
    image: confluentinc/cp-kafka:7.1.1
    hostname: broker
    container_name: broker
    restart: always
    networks:
      - tennisnet
    ports:
      - "9092:9092"
      - "9101:9101"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOPIC_CREATION_ENABLE: 1
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_MESSAGE_MAX_BYTES: 10485880
    volumes:
      - broker0:/var/lib/kafka/data
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    networks:
      - tennisnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tenis
      POSTGRES_PASSWORD: 2sfcNavA89A294V4
      POSTGRES_DB: tenis
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresql:/var/lib/postgresql/data
  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    networks:
      - tennisnet
    ports:
      - "6379:6379"
    depends_on:
      - postgres
  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    restart: always
    networks:
      - tennisnet
    ports:
      - "9000:9000"
    depends_on:
      - broker
    environment:
      KAFKA_BROKERCONNECT: "broker:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
  triton:
    image: nvcr.io/nvidia/tritonserver:22.05-py3 #tritonserver:latest 
    entrypoint: /bin/bash
    #command: -c "cd /models && /opt/tritonserver/bin/tritonserver --model-repository=/models --allow-gpu-metrics=False --strict-model-config=false --pinned-memory-pool-byte-size 5368709120 --cuda-memory-pool-byte-size 0:64 --backend-config='tensorrt','default-max-batch-size'='0'"
    command: -c "cd /models && /opt/tritonserver/bin/tritonserver --model-repository=/models --allow-gpu-metrics=False --strict-model-config=false --backend-config='tensorrt','default-max-batch-size'='0'"
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - models:/models
    networks:
      - tennisnet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  #! SERVICES
  mainservice:
    image: mainservice
    build:
      context: "../Services/server-1 (MainServer)/"
      dockerfile: dockerfile
    hostname: mainservice
    container_name: mainservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50011:50011"
  detectcourtlinesservice:
    image: detectcourtlinesservice
    build:
      context: "../Services/server-2 (Algorithms)/DCL/"
      dockerfile: dockerfile
    hostname: detectcourtlinesservice
    container_name: detectcourtlinesservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50021:50021"
  predictfallpositionservice:
    image: predictfallpositionservice
    build:
      context: "../Services/server-2 (Algorithms)/PFP/"
      dockerfile: dockerfile
    hostname: predictfallpositionservice
    container_name: predictfallpositionservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50023:50023"
  processdataservice:
    image: processdataservice
    build:
      context: "../Services/server-2 (Algorithms)/PD/"
      dockerfile: dockerfile
    hostname: processdataservice
    container_name: processdataservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50024:50024"
  trackballservice:
    image: trackballservice
    build:
      context: "../Services/server-2 (Algorithms)/TB/"
      dockerfile: dockerfile
    hostname: trackballservice
    container_name: trackballservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50022:50022"
    depends_on:
      - triton
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  producerservice:
    image: producerservice
    build:
      context: "../Services/server-3 (StreamKafka)/server 3.1 (Producer)/"
      dockerfile: dockerfile

    hostname: producerservice
    container_name: producerservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50031:50031"
    volumes:
      - assets:/assets
  consumerservice:
    image: consumerservice
    build:
      context: "../Services/server-3 (StreamKafka)/server-3.2 (Consumer)/"
      dockerfile: dockerfile
    hostname: consumerservice
    container_name: consumerservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50032:50032"
    depends_on:
      - producerservice
  postgresservice:
    image: postgresservice
    build:
      context: "../Services/server-4 (Postgresql)/"
      dockerfile: dockerfile
    hostname: postgresservice
    container_name: postgresservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50041:50041"
  redisservice:
    image: redisservice
    build:
      context: "../Services/server-5 (Redis)/"
      dockerfile: dockerfile
    hostname: redisservice
    container_name: redisservice
    restart: always
    networks:
      - tennisnet
    ports:
      - "50051:50051"
    depends_on:
      - postgresservice

#! VOLUMES
volumes:
  broker0:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/broker0"
  zookeeper_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/zookeeper_data"
  zookeeper_log:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/zookeeper_log"
  postgresql:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/postgresql"
  models:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/models"
  assets:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,nolock,soft,rw"
      device: ":/srv/nfs/mydata/docker-tennis/assets"

#! NETWORK
networks:
  tennisnet:
    driver: bridge
