# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redisCache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10redisCache.proto\x12\x08producer\"$\n\x13isCachedDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\"\n\x11writeCacheRequest\x12\r\n\x05query\x18\x01 \x01(\x0c\"%\n\x14readCacheDataRequest\x12\r\n\x05query\x18\x01 \x01(\x0c\" \n\x10isCachedResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"!\n\x12writeCacheResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x11readCacheResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xec\x01\n\nredisCache\x12I\n\nwriteCache\x12\x1b.producer.writeCacheRequest\x1a\x1c.producer.writeCacheResponse\"\x00\x12G\n\x08isCached\x12\x1d.producer.isCachedDataRequest\x1a\x1a.producer.isCachedResponse\"\x00\x12J\n\treadCache\x12\x1e.producer.readCacheDataRequest\x1a\x1b.producer.readCacheResponse\"\x00\x62\x06proto3')



_ISCACHEDDATAREQUEST = DESCRIPTOR.message_types_by_name['isCachedDataRequest']
_WRITECACHEREQUEST = DESCRIPTOR.message_types_by_name['writeCacheRequest']
_READCACHEDATAREQUEST = DESCRIPTOR.message_types_by_name['readCacheDataRequest']
_ISCACHEDRESPONSE = DESCRIPTOR.message_types_by_name['isCachedResponse']
_WRITECACHERESPONSE = DESCRIPTOR.message_types_by_name['writeCacheResponse']
_READCACHERESPONSE = DESCRIPTOR.message_types_by_name['readCacheResponse']
isCachedDataRequest = _reflection.GeneratedProtocolMessageType('isCachedDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _ISCACHEDDATAREQUEST,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:producer.isCachedDataRequest)
  })
_sym_db.RegisterMessage(isCachedDataRequest)

writeCacheRequest = _reflection.GeneratedProtocolMessageType('writeCacheRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITECACHEREQUEST,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:producer.writeCacheRequest)
  })
_sym_db.RegisterMessage(writeCacheRequest)

readCacheDataRequest = _reflection.GeneratedProtocolMessageType('readCacheDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _READCACHEDATAREQUEST,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:producer.readCacheDataRequest)
  })
_sym_db.RegisterMessage(readCacheDataRequest)

isCachedResponse = _reflection.GeneratedProtocolMessageType('isCachedResponse', (_message.Message,), {
  'DESCRIPTOR' : _ISCACHEDRESPONSE,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:producer.isCachedResponse)
  })
_sym_db.RegisterMessage(isCachedResponse)

writeCacheResponse = _reflection.GeneratedProtocolMessageType('writeCacheResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITECACHERESPONSE,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:producer.writeCacheResponse)
  })
_sym_db.RegisterMessage(writeCacheResponse)

readCacheResponse = _reflection.GeneratedProtocolMessageType('readCacheResponse', (_message.Message,), {
  'DESCRIPTOR' : _READCACHERESPONSE,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:producer.readCacheResponse)
  })
_sym_db.RegisterMessage(readCacheResponse)

_REDISCACHE = DESCRIPTOR.services_by_name['redisCache']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ISCACHEDDATAREQUEST._serialized_start=30
  _ISCACHEDDATAREQUEST._serialized_end=66
  _WRITECACHEREQUEST._serialized_start=68
  _WRITECACHEREQUEST._serialized_end=102
  _READCACHEDATAREQUEST._serialized_start=104
  _READCACHEDATAREQUEST._serialized_end=141
  _ISCACHEDRESPONSE._serialized_start=143
  _ISCACHEDRESPONSE._serialized_end=175
  _WRITECACHERESPONSE._serialized_start=177
  _WRITECACHERESPONSE._serialized_end=210
  _READCACHERESPONSE._serialized_start=212
  _READCACHERESPONSE._serialized_end=245
  _REDISCACHE._serialized_start=248
  _REDISCACHE._serialized_end=484
# @@protoc_insertion_point(module_scope)
