# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MainServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10MainServer.proto\x12\x04main\",\n\x17StartProcessRequestData\x12\x11\n\tProcessId\x18\x01 \x01(\x01\"+\n\x16StopProcessRequestData\x12\x11\n\tProcessId\x18\x01 \x01(\x01\"9\n\x18StartProcessResponseData\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\t\"*\n\x17StopProcessResponseData\x12\x0f\n\x07Message\x18\x01 \x01(\t2\xab\x01\n\nMainServer\x12O\n\x0cStartProcess\x12\x1d.main.StartProcessRequestData\x1a\x1e.main.StartProcessResponseData\"\x00\x12L\n\x0bStopProcess\x12\x1c.main.StopProcessRequestData\x1a\x1d.main.StopProcessResponseData\"\x00\x62\x06proto3')



_STARTPROCESSREQUESTDATA = DESCRIPTOR.message_types_by_name['StartProcessRequestData']
_STOPPROCESSREQUESTDATA = DESCRIPTOR.message_types_by_name['StopProcessRequestData']
_STARTPROCESSRESPONSEDATA = DESCRIPTOR.message_types_by_name['StartProcessResponseData']
_STOPPROCESSRESPONSEDATA = DESCRIPTOR.message_types_by_name['StopProcessResponseData']
StartProcessRequestData = _reflection.GeneratedProtocolMessageType('StartProcessRequestData', (_message.Message,), {
  'DESCRIPTOR' : _STARTPROCESSREQUESTDATA,
  '__module__' : 'MainServer_pb2'
  # @@protoc_insertion_point(class_scope:main.StartProcessRequestData)
  })
_sym_db.RegisterMessage(StartProcessRequestData)

StopProcessRequestData = _reflection.GeneratedProtocolMessageType('StopProcessRequestData', (_message.Message,), {
  'DESCRIPTOR' : _STOPPROCESSREQUESTDATA,
  '__module__' : 'MainServer_pb2'
  # @@protoc_insertion_point(class_scope:main.StopProcessRequestData)
  })
_sym_db.RegisterMessage(StopProcessRequestData)

StartProcessResponseData = _reflection.GeneratedProtocolMessageType('StartProcessResponseData', (_message.Message,), {
  'DESCRIPTOR' : _STARTPROCESSRESPONSEDATA,
  '__module__' : 'MainServer_pb2'
  # @@protoc_insertion_point(class_scope:main.StartProcessResponseData)
  })
_sym_db.RegisterMessage(StartProcessResponseData)

StopProcessResponseData = _reflection.GeneratedProtocolMessageType('StopProcessResponseData', (_message.Message,), {
  'DESCRIPTOR' : _STOPPROCESSRESPONSEDATA,
  '__module__' : 'MainServer_pb2'
  # @@protoc_insertion_point(class_scope:main.StopProcessResponseData)
  })
_sym_db.RegisterMessage(StopProcessResponseData)

_MAINSERVER = DESCRIPTOR.services_by_name['MainServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTPROCESSREQUESTDATA._serialized_start=26
  _STARTPROCESSREQUESTDATA._serialized_end=70
  _STOPPROCESSREQUESTDATA._serialized_start=72
  _STOPPROCESSREQUESTDATA._serialized_end=115
  _STARTPROCESSRESPONSEDATA._serialized_start=117
  _STARTPROCESSRESPONSEDATA._serialized_end=174
  _STOPPROCESSRESPONSEDATA._serialized_start=176
  _STOPPROCESSRESPONSEDATA._serialized_end=218
  _MAINSERVER._serialized_start=221
  _MAINSERVER._serialized_end=392
# @@protoc_insertion_point(module_scope)
