# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redisCache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10redisCache.proto\x12\x05redis\"+\n\x0bReadRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05\x66orce\x18\x02 \x01(\x08\"\x1d\n\x0cWriteRequest\x12\r\n\x05query\x18\x01 \x01(\x0c\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\rWriteResponse\x12\x0b\n\x03key\x18\x01 \x01(\t2u\n\nredisCache\x12\x31\n\x04Read\x12\x12.redis.ReadRequest\x1a\x13.redis.ReadResponse\"\x00\x12\x34\n\x05Write\x12\x13.redis.WriteRequest\x1a\x14.redis.WriteResponse\"\x00\x62\x06proto3')



_READREQUEST = DESCRIPTOR.message_types_by_name['ReadRequest']
_WRITEREQUEST = DESCRIPTOR.message_types_by_name['WriteRequest']
_READRESPONSE = DESCRIPTOR.message_types_by_name['ReadResponse']
_WRITERESPONSE = DESCRIPTOR.message_types_by_name['WriteResponse']
ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:redis.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEREQUEST,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:redis.WriteRequest)
  })
_sym_db.RegisterMessage(WriteRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:redis.ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

WriteResponse = _reflection.GeneratedProtocolMessageType('WriteResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITERESPONSE,
  '__module__' : 'redisCache_pb2'
  # @@protoc_insertion_point(class_scope:redis.WriteResponse)
  })
_sym_db.RegisterMessage(WriteResponse)

_REDISCACHE = DESCRIPTOR.services_by_name['redisCache']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READREQUEST._serialized_start=27
  _READREQUEST._serialized_end=70
  _WRITEREQUEST._serialized_start=72
  _WRITEREQUEST._serialized_end=101
  _READRESPONSE._serialized_start=103
  _READRESPONSE._serialized_end=131
  _WRITERESPONSE._serialized_start=133
  _WRITERESPONSE._serialized_end=161
  _REDISCACHE._serialized_start=163
  _REDISCACHE._serialized_end=280
# @@protoc_insertion_point(module_scope)
