# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerDetector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PlayerDetector.proto\x12\x0eplayerdetector\"\xef\x01\n\x08Response\x12\x34\n\x04\x43ode\x18\x01 \x01(\x0e\x32&.playerdetector.Response.ResponseCodes\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x03 \x01(\x0c\"\x8d\x01\n\rResponseCodes\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x08\n\x04INFO\x10\x03\x12\x08\n\x04NULL\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x0c\n\x08REQUIRED\x10\x06\x12\x10\n\x0cUNSUFFICIENT\x10\x07\x12\x14\n\x10\x43ONNECTION_ERROR\x10\x08\"7\n\x05\x46rame\x12\r\n\x05\x42ytes\x18\x01 \x01(\x0c\x12\t\n\x01H\x18\x02 \x01(\x05\x12\t\n\x01W\x18\x03 \x01(\x05\x12\t\n\x01\x43\x18\x04 \x01(\x05\"5\n\rDetectRequest\x12$\n\x05\x46rame\x18\x01 \x01(\x0b\x32\x15.playerdetector.Frame\"<\n\x0e\x44\x65tectResponse\x12*\n\x08Response\x18\x01 \x01(\x0b\x32\x18.playerdetector.Response2[\n\x0ePlayerDetector\x12I\n\x06\x44\x65tect\x12\x1d.playerdetector.DetectRequest\x1a\x1e.playerdetector.DetectResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerDetector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=41
  _RESPONSE._serialized_end=280
  _RESPONSE_RESPONSECODES._serialized_start=139
  _RESPONSE_RESPONSECODES._serialized_end=280
  _FRAME._serialized_start=282
  _FRAME._serialized_end=337
  _DETECTREQUEST._serialized_start=339
  _DETECTREQUEST._serialized_end=392
  _DETECTRESPONSE._serialized_start=394
  _DETECTRESPONSE._serialized_end=454
  _PLAYERDETECTOR._serialized_start=456
  _PLAYERDETECTOR._serialized_end=547
# @@protoc_insertion_point(module_scope)
