# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mainRouterServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16mainRouterServer.proto\x12\x06stream\"\x1b\n\x0brequestData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\x0cresponseData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"@\n!gameObservationControllerResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x32\xd2\x04\n\x10mainRouterServer\x12I\n\x1a\x64\x65tectCourtLinesController\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x12]\n\x19gameObservationController\x12\x13.stream.requestData\x1a).stream.gameObservationControllerResponse\"\x00\x12\x41\n\x12getProducerThreads\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x12:\n\x0bstopProduce\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x12\x45\n\x16stopAllProducerThreads\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x12\x42\n\x13getRunningConsumers\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x12\x42\n\x13stopRunningConsumer\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x12\x46\n\x17stopAllRunningConsumers\x12\x13.stream.requestData\x1a\x14.stream.responseData\"\x00\x62\x06proto3')



_REQUESTDATA = DESCRIPTOR.message_types_by_name['requestData']
_RESPONSEDATA = DESCRIPTOR.message_types_by_name['responseData']
_GAMEOBSERVATIONCONTROLLERRESPONSE = DESCRIPTOR.message_types_by_name['gameObservationControllerResponse']
requestData = _reflection.GeneratedProtocolMessageType('requestData', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'mainRouterServer_pb2'
  # @@protoc_insertion_point(class_scope:stream.requestData)
  })
_sym_db.RegisterMessage(requestData)

responseData = _reflection.GeneratedProtocolMessageType('responseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'mainRouterServer_pb2'
  # @@protoc_insertion_point(class_scope:stream.responseData)
  })
_sym_db.RegisterMessage(responseData)

gameObservationControllerResponse = _reflection.GeneratedProtocolMessageType('gameObservationControllerResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMEOBSERVATIONCONTROLLERRESPONSE,
  '__module__' : 'mainRouterServer_pb2'
  # @@protoc_insertion_point(class_scope:stream.gameObservationControllerResponse)
  })
_sym_db.RegisterMessage(gameObservationControllerResponse)

_MAINROUTERSERVER = DESCRIPTOR.services_by_name['mainRouterServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTDATA._serialized_start=34
  _REQUESTDATA._serialized_end=61
  _RESPONSEDATA._serialized_start=63
  _RESPONSEDATA._serialized_end=91
  _GAMEOBSERVATIONCONTROLLERRESPONSE._serialized_start=93
  _GAMEOBSERVATIONCONTROLLERRESPONSE._serialized_end=157
  _MAINROUTERSERVER._serialized_start=160
  _MAINROUTERSERVER._serialized_end=754
# @@protoc_insertion_point(module_scope)
