# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import testServer_pb2 as testServer__pb2


class TestServerStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_stream(
                '/test.TestServer/Process',
                request_serializer=testServer__pb2.requestData.SerializeToString,
                response_deserializer=testServer__pb2.responseData.FromString,
                )


class TestServerServicer(object):
    """Service
    """

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=testServer__pb2.requestData.FromString,
                    response_serializer=testServer__pb2.responseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.TestServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestServer(object):
    """Service
    """

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/test.TestServer/Process',
            testServer__pb2.requestData.SerializeToString,
            testServer__pb2.responseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
