# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import conf.PlayerDetector_pb2 as PlayerDetector__pb2


class PlayerDetectorStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/playerdetector.PlayerDetector/Detect',
                request_serializer=PlayerDetector__pb2.DetectRequest.SerializeToString,
                response_deserializer=PlayerDetector__pb2.DetectResponse.FromString,
                )


class PlayerDetectorServicer(object):
    """Service
    """

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerDetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=PlayerDetector__pb2.DetectRequest.FromString,
                    response_serializer=PlayerDetector__pb2.DetectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'playerdetector.PlayerDetector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerDetector(object):
    """Service
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/playerdetector.PlayerDetector/Detect',
            PlayerDetector__pb2.DetectRequest.SerializeToString,
            PlayerDetector__pb2.DetectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
