# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11processData.proto\x12\x05\x63\x61\x63he\"0\n\x11processAOSRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"1\n\x12processAOSResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32R\n\x0bProcessData\x12\x43\n\nprocessAOS\x12\x18.cache.processAOSRequest\x1a\x19.cache.processAOSResponse\"\x00\x62\x06proto3')



_PROCESSAOSREQUEST = DESCRIPTOR.message_types_by_name['processAOSRequest']
_PROCESSAOSRESPONSE = DESCRIPTOR.message_types_by_name['processAOSResponse']
processAOSRequest = _reflection.GeneratedProtocolMessageType('processAOSRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSAOSREQUEST,
  '__module__' : 'processData_pb2'
  # @@protoc_insertion_point(class_scope:cache.processAOSRequest)
  })
_sym_db.RegisterMessage(processAOSRequest)

processAOSResponse = _reflection.GeneratedProtocolMessageType('processAOSResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSAOSRESPONSE,
  '__module__' : 'processData_pb2'
  # @@protoc_insertion_point(class_scope:cache.processAOSResponse)
  })
_sym_db.RegisterMessage(processAOSResponse)

_PROCESSDATA = DESCRIPTOR.services_by_name['ProcessData']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSAOSREQUEST._serialized_start=28
  _PROCESSAOSREQUEST._serialized_end=76
  _PROCESSAOSRESPONSE._serialized_start=78
  _PROCESSAOSRESPONSE._serialized_end=127
  _PROCESSDATA._serialized_start=129
  _PROCESSDATA._serialized_end=211
# @@protoc_insertion_point(module_scope)
