# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clients.ExtraProcess.conf.ExtraProcess_pb2 as ExtraProcess__pb2


class ExtraProcessStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MergeData = channel.unary_unary(
                '/extraprocess.ExtraProcess/MergeData',
                request_serializer=ExtraProcess__pb2.ExtraProcessRequest.SerializeToString,
                response_deserializer=ExtraProcess__pb2.ExtraProcessResponse.FromString,
                )


class ExtraProcessServicer(object):
    """Service
    """

    def MergeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtraProcessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MergeData': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeData,
                    request_deserializer=ExtraProcess__pb2.ExtraProcessRequest.FromString,
                    response_serializer=ExtraProcess__pb2.ExtraProcessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'extraprocess.ExtraProcess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExtraProcess(object):
    """Service
    """

    @staticmethod
    def MergeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/extraprocess.ExtraProcess/MergeData',
            ExtraProcess__pb2.ExtraProcessRequest.SerializeToString,
            ExtraProcess__pb2.ExtraProcessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
