# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraProcess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x45xtraProcess.proto\x12\x0c\x65xtraprocess\"#\n\x13\x45xtraProcessRequest\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\"\'\n\x14\x45xtraProcessResponse\x12\x0f\n\x07Message\x18\x01 \x01(\t2d\n\x0c\x45xtraProcess\x12T\n\tMergeData\x12!.extraprocess.ExtraProcessRequest\x1a\".extraprocess.ExtraProcessResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExtraProcess_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTRAPROCESSREQUEST._serialized_start=36
  _EXTRAPROCESSREQUEST._serialized_end=71
  _EXTRAPROCESSRESPONSE._serialized_start=73
  _EXTRAPROCESSRESPONSE._serialized_end=112
  _EXTRAPROCESS._serialized_start=114
  _EXTRAPROCESS._serialized_end=214
# @@protoc_insertion_point(module_scope)
