# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detectCourtLines.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65tectCourtLines.proto\x12\x05\x63\x61\x63he\")\n\x18\x65xtractCourtLinesRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"*\n\x19\x65xtractCourtLinesResponse\x12\r\n\x05point\x18\x01 \x01(\x0c\x32k\n\x0f\x64\x65tectCourtLine\x12X\n\x11\x65xtractCourtLines\x12\x1f.cache.extractCourtLinesRequest\x1a .cache.extractCourtLinesResponse\"\x00\x62\x06proto3')



_EXTRACTCOURTLINESREQUEST = DESCRIPTOR.message_types_by_name['extractCourtLinesRequest']
_EXTRACTCOURTLINESRESPONSE = DESCRIPTOR.message_types_by_name['extractCourtLinesResponse']
extractCourtLinesRequest = _reflection.GeneratedProtocolMessageType('extractCourtLinesRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTCOURTLINESREQUEST,
  '__module__' : 'detectCourtLines_pb2'
  # @@protoc_insertion_point(class_scope:cache.extractCourtLinesRequest)
  })
_sym_db.RegisterMessage(extractCourtLinesRequest)

extractCourtLinesResponse = _reflection.GeneratedProtocolMessageType('extractCourtLinesResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTCOURTLINESRESPONSE,
  '__module__' : 'detectCourtLines_pb2'
  # @@protoc_insertion_point(class_scope:cache.extractCourtLinesResponse)
  })
_sym_db.RegisterMessage(extractCourtLinesResponse)

_DETECTCOURTLINE = DESCRIPTOR.services_by_name['detectCourtLine']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTRACTCOURTLINESREQUEST._serialized_start=33
  _EXTRACTCOURTLINESREQUEST._serialized_end=74
  _EXTRACTCOURTLINESRESPONSE._serialized_start=76
  _EXTRACTCOURTLINESRESPONSE._serialized_end=118
  _DETECTCOURTLINE._serialized_start=120
  _DETECTCOURTLINE._serialized_end=227
# @@protoc_insertion_point(module_scope)
