# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detectCourtLines_pb2 as detectCourtLines__pb2


class detectCourtLineStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.extractCourtLines = channel.unary_unary(
                '/cache.detectCourtLine/extractCourtLines',
                request_serializer=detectCourtLines__pb2.extractCourtLinesRequest.SerializeToString,
                response_deserializer=detectCourtLines__pb2.extractCourtLinesResponse.FromString,
                )


class detectCourtLineServicer(object):
    """Service
    """

    def extractCourtLines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_detectCourtLineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'extractCourtLines': grpc.unary_unary_rpc_method_handler(
                    servicer.extractCourtLines,
                    request_deserializer=detectCourtLines__pb2.extractCourtLinesRequest.FromString,
                    response_serializer=detectCourtLines__pb2.extractCourtLinesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache.detectCourtLine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class detectCourtLine(object):
    """Service
    """

    @staticmethod
    def extractCourtLines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache.detectCourtLine/extractCourtLines',
            detectCourtLines__pb2.extractCourtLinesRequest.SerializeToString,
            detectCourtLines__pb2.extractCourtLinesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
