# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10testServer.proto\x12\x04test\"\x1b\n\x0brequestData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1c\n\x0cresponseData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2B\n\nTestServer\x12\x34\n\x07Process\x12\x11.test.requestData\x1a\x12.test.responseData\"\x00\x30\x01\x62\x06proto3')



_REQUESTDATA = DESCRIPTOR.message_types_by_name['requestData']
_RESPONSEDATA = DESCRIPTOR.message_types_by_name['responseData']
requestData = _reflection.GeneratedProtocolMessageType('requestData', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'testServer_pb2'
  # @@protoc_insertion_point(class_scope:test.requestData)
  })
_sym_db.RegisterMessage(requestData)

responseData = _reflection.GeneratedProtocolMessageType('responseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'testServer_pb2'
  # @@protoc_insertion_point(class_scope:test.responseData)
  })
_sym_db.RegisterMessage(responseData)

_TESTSERVER = DESCRIPTOR.services_by_name['TestServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTDATA._serialized_start=26
  _REQUESTDATA._serialized_end=53
  _RESPONSEDATA._serialized_start=55
  _RESPONSEDATA._serialized_end=83
  _TESTSERVER._serialized_start=85
  _TESTSERVER._serialized_end=151
# @@protoc_insertion_point(module_scope)
